### ISSUE TITLE
请问 allowEmpty 可以和 长度限定 一起使用吗?

### ISSUE THREAD

**Issue by solarhell** [node-modules/parameter#21]
```javascript
        someField: {
          type: 'string',
          required: false,
          allowEmpty: true,
          min: 6,
          max: 20,
        }
```

这个field可为空，如果不为空则限定长度。
BTW, 这个issue和 #20 有关吗？
谢谢。

**Comment by dead-horse** [comment]
可以，调整一下位置好了，先支持 allowEmpty

**Comment by solarhell** [comment]
您好 调整为
 ```
someField: {
  type: 'string',
  allowEmpty: true,
  required: false,
  min: 6,
  max: 20,
}
```
还是会报最小长度要大于6

**Comment by dead-horse** [comment]
我说我那个 PR 要调整一下校验顺序

**Comment by dead-horse** [comment]
等 #20 改改合并了再试

**Comment by xjchenhao** [comment]
作者你好，npm上还是2.0.0哦。 @dead-horse

**Comment by dead-horse** [comment]
@xjchenhao 发布了

**Comment by solarhell** [comment]
还是不能work，我的code和测试用例一样
![image](https://cloud.githubusercontent.com/assets/10279583/26763251/450f35b2-4982-11e7-9584-4e894d3d7646.png)
![image](https://cloud.githubusercontent.com/assets/10279583/26763244/196851d2-4982-11e7-8580-039a07154ce3.png)
![image](https://cloud.githubusercontent.com/assets/10279583/26763246/247a11fa-4982-11e7-9b06-54705af1432a.png)
![image](https://cloud.githubusercontent.com/assets/10279583/26763248/31d5ed06-4982-11e7-8fcc-6194d359d63c.png)

**Comment by dead-horse** [comment]
我这正常的，你看看版本，是不是真的引用到了新版本的 parameter

![image](https://cloud.githubusercontent.com/assets/985607/26763483/1bf3f3bc-4986-11e7-81ba-fc18bf275081.png)

**Comment by dead-horse** [comment]
或者你写一个更简单的用例来测试一下吧

**Comment by solarhell** [comment]
谢谢，确实是因为npm缓存的问题。当时手动 `npm install parameter@latest`，可能这样不行。
