### ISSUE TITLE
有多余的参数不会抛出异常

### ISSUE THREAD

**Issue by freebyron** [node-modules/parameter#27]
## example
`
var Rule = {
    name: { type: 'string' },
    password: { type: 'string' },
};

var shouldThrowError = {
    "name":"test",
    "password":"test",
    "password2":"test"
}
`

实际上会验证成功，至少应该有可以配置不能有多余参数的配置

**Comment by dead-horse** [comment]
不关心是否有多余的参数，你不读它就可以了，parameter 只关心配置中的参数以及类型

**Comment by onweer** [comment]
如果想要直接用ctx.request.body就不行了, 必须手动再pick一次rule里面的属性.. 或者有没有方法能拿到验证后的值?  默认好像只返回errors  @dead-horse
