### ISSUE TITLE
合法的url check不通过

### ISSUE THREAD

**Issue by kylezhang** [node-modules/parameter#43]
### 待测试的url：
```
"long_url": "http://jice.io?utm_campaign=123",
```

### 测试结果：
![image](https://user-images.githubusercontent.com/3679798/42301431-c685eb3e-8047-11e8-8b6b-5af86b80b7a1.png)

> 试了下把参数的的部分，`?`前面加上`/`就可以通过。

### 修改后的url：
```
"long_url": "http://jice.io/?utm_campaign=123",
```

**Comment by dead-horse** [comment]
应为修改后的 url 才是合法的 url

**Comment by kylezhang** [comment]
嗯，感谢回复
但是不修改也可以使用
