### ISSUE TITLE
how to validate a array and the item of array is enum ?

### ISSUE THREAD

**Issue by zaleGZL** [node-modules/parameter#57]
such as:

```
{
    color: ['red', 'blue', 'black']
}
```

**Comment by catherinessssss** [comment]
Hi @zaleGZL , have you solved this issue?

**Comment by xsdlr** [comment]
for example color have four values： 'red', 'blue', 'black', 'white'
````
const data = [{
    color: ['red', 'blue', 'black']
}];

const rule = {
  color: {
    type: 'array',
    itemType: 'enum',
    rule: {
      values: ['red', 'blue', 'black', 'white'],
    },
  },
};

const error = validate(rule, data);

````

**Comment by catherinessssss** [comment]
> for example color have four values： 'red', 'blue', 'black', 'white'
> 
> ```
> const data = [{
>     color: ['red', 'blue', 'black']
> }];
> 
> const rule = {
>   color: {
>     type: 'array',
>     itemType: 'enum',
>     rule: {
>       values: ['red', 'blue', 'black', 'white'],
>     },
>   },
> };
> 
> const error = validate(rule, data);
> ```

Thanks!
