### ISSUE TITLE
当参数传多了时，无法检测到异常。

### ISSUE THREAD

**Issue by brizer** [node-modules/parameter#73]
``` js
var Parameter = require('parameter');
const parameter = new Parameter(

);

var data = {
  name: 'foo',
  age: 24,
  gender: 'male',
  xixi: 'haha'
};

var rule = {
  name: {type:'string'},
  age: 'int',
  gender: ['male', 'female', 'unknown']
};

var errors = parameter.validate(rule, data);
console.log(errors)
```

这种情况下无法检测到xixi是不合法的。
我觉得应该提供一个参数来配置。

**Comment by dead-horse** [comment]
我们的实践是会实现一个包装的方法，来实现只获取 rule 定义了规则的属性。

```js
const params = validateAndPermit(rule, data);
```

**Comment by brizer** [comment]
> 我们的实践是会实现一个包装的方法，来实现只获取 rule 定义了规则的属性。
> 
> ```js
> const params = validateAndPermit(rule, data);
> ```

恩恩，这样也是一种方式。就是如果想提示客户端，需要手动再抛回去了。可以的。

**Comment by dead-horse** [comment]
其实一般来说也不需要提示客户端了，我们都是直接忽略掉哪些多余的参数。除非还有对参数的签名逻辑需要提醒用户。

**Comment by brizer** [comment]
> 其实一般来说也不需要提示客户端了，我们都是直接忽略掉哪些多余的参数。除非还有对参数的签名逻辑需要提醒用户。

Thanks.
