### ISSUE TITLE
int 验证规则有问题

### ISSUE THREAD

**Issue by qq578023708** [node-modules/parameter#84]
验证数据类型为  int ,    
当POST提交的数据为     aa              ,  验证不通过
当POST提交的数据为     aa123        ,  验证不通过
当POST提交的数据为    123aa        ,   验证通过

这是不是属于个 bug

`const {ctx}=this;
        let rules={
            fdate:{type:'string'},
            fdept:{type:'int'},
            fid:{type:'string'},
        };
        try{
            ctx.validate(rules,ctx.request.body);
        }catch(err){
            ctx.body={
                code: -1,
                msg: err
            };
            return;
        }`

**Comment by chenkai0520** [comment]
123aa 转成123了

https://github.com/node-modules/parameter/blob/6e252719803a583a778541f46d7d581f248258f3/index.js#L284-L286
