### ISSUE TITLE
需要 I18n，所以返回验证信息里面的 message 不应该保函 key 的字符串

### ISSUE THREAD

**Issue by huacnlee** [node-modules/parameter#9]
https://github.com/node-modules/parameter/blob/master/index.js#L101

```js
[
{
  message: 'name should be a string',
  code: 'invalid',
  field: 'name'
}  
]
```

to

```js
[
{
  message: 'should be a string',
  code: 'invalid',
  field: 'name'
}  
]
```

这样一来，message 的内容是固定的，就可以写 I18n 对应其他语言了。

**Comment by fengmk2** [comment]
LGTM, DO IT!

**Comment by fengmk2** [comment]
@huacnlee add you to team now.

**Comment by huacnlee** [comment]
@fengmk2 我来搞吧？

**Comment by huacnlee** [comment]
看了一下 `should bigger than 10` 这种情况还无法实现 I18n，10 是变数，存在困难，除非这个库直接带 i18n, 可以支持配置。
