### ISSUE TITLE
when I use http://127.0.0.1:80 in url rule,I got should be a url error

### ISSUE THREAD

**Issue by phant0m4o4** [node-modules/parameter#92]
when I use http://127.0.0.1:80 in url rule,I got should be a url error

**Comment by fengmk2** [comment]
这是 by design 的，private & local networks 都是认为非法 url。
https://gist.github.com/dperini/729294#file-regex-weburl-js-L78

如果你需要更大范围，那么你可以通过自定义 url 规则来实现。
